version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 && --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodeapp
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  nginxserver:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    networks:
      - nodenet
    container_name: nginxapp
  nodeserver:
    build: 
      context: .
      dockerfile: Dockerfile.node
    networks:
      - nodenet
    container_name: nodeapp

networks:
  nodenet:
    driver: bridge