version: '3'

services:
  db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./exec.sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodeapp
    networks:
      - nodenet
  nginxserver:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    networks:
      - nodenet
    container_name: nginxapp
  nodeserver:
    build: 
      context: .
      dockerfile: Dockerfile.node
    networks:
      - nodenet
    container_name: nodeapp

networks:
  nodenet:
    driver: bridge